language: php

php: 
  - hhvm
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - nightly

before_install: 
  - sudo apt-get install nodejs
  - npm install -g grunt-cli

install: 
  - npm install
  - composer install

script: 
  - grunt

after_script: 
  - php vendor/bin/coveralls -v
  - CODECLIMATE_REPO_TOKEN=fbbb8faf1226ee12fa1f4f6b838fb021e0fcfcb4c48a8be1906adedcc255a860 ./code-climat-test-reporter
